### ISSUE TITLE
Climate Talk

### ISSUE THREAD

**Issue by Daniel-dev22** [kdschlosser/libopenzwave#1]
I was not sure how to get in contact with you about this [repo](https://github.com/kdschlosser/ClimateTalk). Did you ever get this working? Especially the micropython esp32 boot script as I don't see that in the code?

Do you think that esphome could be used instead of micropython? I have an econet setup not the Climatetalk 2 setup if this is working what would I need to reverse Engineer it?

https://github.com/kdschlosser/ClimateTalk

Lastly, on topic. Have you heard about zwavejs? I didn't read into what your intent was for this zwave project but zwavejs is very mature.
https://github.com/zwave-js/node-zwave-js

**Comment by kdschlosser** [comment]
the problem with zwavejs is it uses java. an intermediate transport layer like MQTT needs to be used in order to use it. Plus it is written using an upper level programming language that is harder to use than Python.

I also looked at the way it was written and it is not really all that "user friendly" from the standpoint of a programmer in terms of adding a GUI to it.

There is also several other features I have built into the library that enables a user to do things like install the library onto a raspberry pi and have it run as a daemon and then install the same library onto an actual computer to handle all of the GUI related stuff and the 2 will talk to each other keeping the API exactly the same as if it was accessing the ZStick directly. There is also the  ability to detach the ZWave stack from the GUI so if needing to restart the GUI for some reason the ZWave stack will not restart with it. There is also a speed factor.  A network with 200 nodes will populate everything except for controlling a device in < 10 seconds.

ClimateTalk and EcoNet are not the same protocol. EcoNet started off as ClimateTalk but so much of it has changed it's not really the same anymore. The communications is also encrypted so unless you know how to break that encryption the information you sniff is going to be random jibberish.

I spoke with one of the people that authored the original ClimateTalk Specification and he told me the biggest problem with it was it being changed by the companies that used it. They decided to do whatever they wanted with it without sticking to the API so trying to write a program would have to be done on a device by device basis. It is much like what has happened to ZWave where there is a lack of standardization for configuration settings and only small parts of command classes being implemented.. The switch multilevel command class is a great example of a command class that only gets partly implemented. Most times in an application or "controller" the StartLevelChange and StopLevelChange commands are either not done properly or not done at all. This causes a loss of ramping ability with the switches when a command is sent to set the level.

I personally do not like Java because it is resource hog. The garbage collection routines are terrible and it's just plain bloated and slow.

**Comment by Daniel-dev22** [comment]
> the problem with zwavejs is it uses java. an intermediate transport layer like MQTT needs to be used in order to use it. Plus it is written using an upper level programming language that is harder to use than Python.
> 
> I also looked at the way it was written and it is not really all that "user friendly" from the standpoint of a programmer in terms of adding a GUI to it.
> 
> There is also several other features I have built into the library that enables a user to do things like install the library onto a raspberry pi and have it run as a daemon and then install the same library onto an actual computer to handle all of the GUI related stuff and the 2 will talk to each other keeping the API exactly the same as if it was accessing the ZStick directly. There is also the ability to detach the ZWave stack from the GUI so if needing to restart the GUI for some reason the ZWave stack will not restart with it. There is also a speed factor. A network with 200 nodes will populate everything except for controlling a device in < 10 seconds.
> 
> ClimateTalk and EcoNet are not the same protocol. EcoNet started off as ClimateTalk but so much of it has changed it's not really the same anymore. The communications is also encrypted so unless you know how to break that encryption the information you sniff is going to be random jibberish.
> 
> I spoke with one of the people that authored the original ClimateTalk Specification and he told me the biggest problem with it was it being changed by the companies that used it. They decided to do whatever they wanted with it without sticking to the API so trying to write a program would have to be done on a device by device basis. It is much like what has happened to ZWave where there is a lack of standardization for configuration settings and only small parts of command classes being implemented.. The switch multilevel command class is a great example of a command class that only gets partly implemented. Most times in an application or "controller" the StartLevelChange and StopLevelChange commands are either not done properly or not done at all. This causes a loss of ramping ability with the switches when a command is sent to set the level.
> 
> I personally do not like Java because it is resource hog. The garbage collection routines are terrible and it's just plain bloated and slow.

Interesting points on performance I didn't know that. Zwavejs-ui is mqtt optional. It used to have mqtt in the name which I'm sure confused people.

For econet i replied here to not take this off topic any further. Would you happen to have any ideas of how to break the encryption? https://github.com/kpishere/Net485/issues/1#issuecomment-1328216707

**Comment by kdschlosser** [comment]
not a clue. I do have a Rheem Econet tankless water heater but they do not make a WiFi attachment for it. I tried to use the WiFi part for the tanked water heater but it did not work at all. I would need to have both ends so the 2 pieces could communicate. With just the water heater I am not going to see a whole lot going on.

I am pretty confident that Rheem has more than likely not butchered up too much of the original ClimateTalk protocol but because they have encrypted the communications there is no way to know without breaking through the encryption.

**Comment by Daniel-dev22** [comment]
> not a clue. I do have a Rheem Econet tankless water heater but they do not make a WiFi attachment for it. I tried to use the WiFi part for the tanked water heater but it did not work at all. I would need to have both ends so the 2 pieces could communicate. With just the water heater I am not going to see a whole lot going on.
> 
> I am pretty confident that Rheem has more than likely not butchered up too much of the original ClimateTalk protocol but because they have encrypted the communications there is no way to know without breaking through the encryption.

We have made a ton of progress on decrypting econet on discord if you are interested. I'm the only one with econet HVAC and a water heater. 2 others just have water heaters. A lot of progress is being made. We were able to set our water heater temperature and read it among many other sensors.

If you are interested in helping figure this out please join the discord.

https://discord.gg/huV9Thdh

**Comment by kdschlosser** [comment]
yeah actually I would be interested in seeing what you guys have been up to. I have been working with a graphics framework that will run on an esp32 using MicroPython. The library is pretty powerful in what it can do considering it is made for devices with very limited resources like the ESP32.

Here are some examples of what it is able to do. These are things I wrote the code for myself.
https://www.youtube.com/watch?v=NxQ7cLobr_Q

https://www.youtube.com/watch?v=Ko-yzwjXRX4

These last 2 are running on an on an ESP32 with a 3.5" display where as the other 2 were running using javascript.

https://www.youtube.com/watch?v=35j4p78OJAs

https://www.youtube.com/watch?v=Yiq3RKSpnZo

With the graphics capabilities in place making a custom thermostat using an ESP32 is a snap to do. the ESP32 I believe has an RS485 interface already built into it.

**Comment by Daniel-dev22** [comment]
That would be really cool to use an esp32 as a digital control thermostat for a water heater/HVAC. Are you controlling anything currently with the esp32 or is that just for studying what's possible?

**Comment by kdschlosser** [comment]
The example with the multiple arcs is being used to control a variable speed electric water pump and variable speed radiator fan on my "project" car.. It monitors 2 temp sensors and does all of the floating point math and calibration using the Steinhardt equations. It also handles controlling the speed of the water pump and the fan. has error detection in the event of a short/open in either the temp sensors or in the wiring for the fan/water pump. It also detects over current/over temperature conditions. Learning code to hit set temperatures and maintain those temps or switch over to manual control. Data logging is also built in as well.

I did the component level design with doing the CAD for the PCB. I sent the designs to have the PCB manufactured for it.

I am just finishing up a design that has 2 ESP32-S3 MCU's on it each having 8MB flash and 8MB of SPIRAM. The 2 are able to communicate with each other. One would be dedicated to the UI and the other for doing calculations and sensor reading. This gives a performance bump of 1600%. It would be able to handle a display that has a resolution of 800 x 480 with 32 bit color. It would almost be able to play video at that resolution. to have the video look good the resolution might need to be lowered a little bit.

**Comment by Daniel-dev22** [comment]
> The example with the multiple arcs is being used to control a variable speed electric water pump and variable speed radiator fan on my "project" car.. It monitors 2 temp sensors and does all of the floating point math and calibration using the Steinhardt equations. It also handles controlling the speed of the water pump and the fan. has error detection in the event of a short/open in either the temp sensors or in the wiring for the fan/water pump. It also detects over current/over temperature conditions. Learning code to hit set temperatures and maintain those temps or switch over to manual control. Data logging is also built in as well.
> 
> I did the component level design with doing the CAD for the PCB. I sent the designs to have the PCB manufactured for it.
> 
> I am just finishing up a design that has 2 ESP32-S3 MCU's on it each having 8MB flash and 8MB of SPIRAM. The 2 are able to communicate with each other. One would be dedicated to the UI and the other for doing calculations and sensor reading. This gives a performance bump of 1600%. It would be able to handle a display that has a resolution of 800 x 480 with 32 bit color. It would almost be able to play video at that resolution. to have the video look good the resolution might need to be lowered a little bit.

What do you do for work to know how to do all of this?

**Comment by kdschlosser** [comment]
has nothing to do with work. I only have a single skill really and that skill is what enables me to be able to do all kinds of things, The only skill you need is knowing how to read... You have the worlds largest single source of information at your fingertips. It's not like it was 30 years ago when the internet didn't exist in it's current form. Access to information was not always as easy as it is now.

Electronics design and programming I got into maybe 7 years ago as something to mess around with. I wanted something to be able to turn on and off my fireplaces using my home automation system and nothing existed. So I made it. I am possibly the first person to use google maps to locate where I am and how far I am away from my home. That data would get sent to my server and it would decide on what needs to be done. If I am 10 miles away and traveling towards my house and my wife isn't home and the temperature outside warrants turning the heat on that is what it does. If I leave the house and no one is here it shuts down the fireplaces. A person rings my doorbell every active TV/computer in my house will have an OSD displayed on it showing the security camera for the front door. If my cell phone rings anything playing on the TV gets paused or if the radio is on it gets muted.

Put it to you this way, If I had a garage I could open the garage door with an x-box controller if I wanted to.

**Comment by kdschlosser** [comment]
I am going to bow out of doing anything on that discord thing. the people there only seem interested in being able to send commands to it using home assistant and not actually figuring out the econet protocol. I am not interested in developing something specifically for the use in a single application that only has partial functionality.

**Comment by Daniel-dev22** [comment]
> I am going to bow out of doing anything on that discord thing. the people there only seem interested in being able to send commands to it using home assistant and not actually figuring out the econet protocol. I am not interested in developing something specifically for the use in a single application that only has partial functionality.

I think we are trying to figure it out by seeing what happens when we do x and then attempting to re-create it. Stockmopar for his water heater is able to read all the diagnostic sensors and control temperature. The goal is to be able to make it possible to not need a Rheem econet app and the esp32 sends and receives all the data. This group has gotten further than any others that have tried to decode econet. No one is an econet expert so it's just a game of trying to understand what everything means.

The HVAC side is where there hasn't been someone as skilled as stockmopar to help with creating code for and that's the side I care most about. The water heater is potentially a stepping stone once to trying to figure out hvac, and once the water heater is figured out the next issue is why the code only works when the esp32 and internal wifi module work together but once it's on the bus with a thermostat and other devices the code stops working.

As noted on discord esphome doesn't require home assistant at all. If you make any progress with decoding the entire protocol for econet and would like to share that would be appreciated.

**Comment by kdschlosser** [comment]
I can tell you that it follows quite a bit of the climate talk protocol. some of the markers are the same as well as responses. I am willing to bet a lot of the low level API stuff is identical. they may have changed or added new commands but I am thinking that there isn't a whole hell of a lot that is different.

**Comment by Daniel-dev22** [comment]
I figured out how the devices join the network including the wifi module. As well as their heartbeat mechanism for alerting the network to a missing device/controller.

Do you see anything that stands out? How do you think timing works with this protocol in terms of when messages can be sent? It appears you can't just send the thermostat a command as if you're the wifi module whenever you please. 


Wifi Module rejoin
https://github.com/stockmopar/esphome-econet/blob/main/logs/hvac_disconnect_reconnect_wifi_module.txt#L2190


Thermostat disconnected for about 2 minutes beginning here.
https://github.com/stockmopar/esphome-econet/blob/main/logs/hvac_log_thermostat_discconnect_then_reconnect.txt#L1887

**Comment by Daniel-dev22** [comment]
We also noticed `AIRHSTAT` returns a weird response something we have never seen before. It contains a lot of data about the airhandler that's for sure as it's the only real response from the airhandler.

```
80.00.03.80.00.80.00.03.C0.00.A0.00.00.06.84.00.00.00.00.00.00.00.00.00.00.DB.01.08.07.EE.02.EE.02.0A.03.04.00.40.06.40.06.00.00.00.00.00.00.00.00.01.00.3E.BF.02.2B.41.43.2D.41.49.52.48.2D.30.30.2D.30.31.2D.31.30.00.42.1A.F6.34.42.64.5B.E5.C2.20.00.00.00.00.01.00.24.00.01.00.00.00.00.00.77.00.00.00.0A.A2.00.00.09.69.00.00.27.57.00.00.00.5F.00.00.01.DE.00.00.01.6B.00.00.45.08.0B.09.00.02.E2.41.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.01.01.00.00.41.D8.00.00.41.0B.EE.E8.42.26.C7.70.42.03.CB.B6.42.EB.AD.80.00.00.00.5B.A8
```
